language: python

python:
- "2.7"
- "3.5"
    
install:
- pip install pytest pytest-cov
- pip install coveralls
- pip install -r requirements.txt
- pip install https://github.com/neurosynth/neurosynth/archive/master.zip

before_script:
- python setup.py install
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3

script:
- py.test --cov-report term-missing --cov=python_gclda

after_success:
- coveralls
